# NumPy Exercises 



#### Import NumPy as np

In [7]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 fives

In [21]:
np.ones((10,), dtype=int) * 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [19]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [20]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [34]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.random()

0.622130581294975

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [38]:
np.random.random(25)


array([0.21388454, 0.87412277, 0.02714996, 0.95551025, 0.13198742,
       0.97190215, 0.8797463 , 0.35565275, 0.00615822, 0.19377344,
       0.79971467, 0.42389469, 0.68125459, 0.85367078, 0.52890828,
       0.4161654 , 0.58684154, 0.10058128, 0.07812076, 0.4800159 ,
       0.95035894, 0.37960269, 0.35621589, 0.72934073, 0.24936169])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [41]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Create the following 2D matrix. 

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

In [9]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
a
a.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in matrix

In [10]:
a.sum()

325

#### Get the standard deviation of the values in matrix

In [12]:
np.std(a)

7.211102550927978

#### Get the sum of all the columns in matrix

In [11]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])